# Generated by Django 5.0.1 on 2024-02-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageoftheday',
            name='descripcion_imagen',
        ),
        migrations.RemoveField(
            model_name='imageoftheday',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='imageoftheday',
            name='titulo_imagen',
        ),
        migrations.AddField(
            model_name='imageoftheday',
            name='image_url',
            field=models.URLField(default='no url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageoftheday',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
