# Generated by Django 5.0.1 on 2024-02-04 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_imageoftheday_descripcion_imagen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageoftheday',
            options={'get_latest_by': 'last_updated'},
        ),
    ]
