# Generated by Django 5.0.1 on 2024-02-01 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoVlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='descripcion',
            field=models.CharField(default='descripcion de la imagen', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 2, 1, 7, 40, 3, 580213, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Files/images'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='lugar',
            field=models.CharField(default='lugar', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(default='titulo', max_length=20),
            preserve_default=False,
        ),
    ]
