# Generated by Django 5.0.1 on 2024-02-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoVlogApp', '0002_publicacion_descripcion_publicacion_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(null=True, upload_to='static/imagenes'),
        ),
    ]
