# Generated by Django 5.0.1 on 2024-02-04 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoVlogApp', '0003_alter_publicacion_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='titulo',
        ),
    ]
