# Generated by Django 5.0.1 on 2024-02-04 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoVlogApp', '0004_remove_publicacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='descripcion',
            field=models.CharField(default='sin descripcion', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 2, 4, 5, 31, 24, 179362, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='lugar',
            field=models.CharField(default='sin lugar', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(default='sin titulo', max_length=20),
            preserve_default=False,
        ),
    ]
